### ISSUE TITLE
Measures against spam?

### ISSUE THREAD

**Issue by fcambus** [echojs/echojs#1]
This has been discussed a few times, adding the links here for reference:

https://www.echojs.com/news/18978
https://www.echojs.com/news/29226
https://www.echojs.com/news/30241

**Comment by fcambus** [comment]
Another discussion: https://www.echojs.com/news/30696

**Comment by tracker1** [comment]
A thought I was having... maybe instead of deleting accounts that repeatedly spam... shadow banning... just marking their posts as already deleted.  Also, might want to do IP tracking on deletions for similar effect.  In general, it kind of sucks.

It's funny, but about half the posts come from 3-4 accounts, the rest come from new accounts created for the one post.
